apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-configmap
  namespace: dev
data:
  application.yaml: |+
    app:
      kafka:
        server: host.minikube.internal:29092
        offset-reset: latest
        topics:
          regist: registation.new
        groupid:
          regist: registation.new.group.2
    server:
      port: 8080