apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  namespace: dev
  labels:
    app: consumer-label
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: consumer-deployment
